export const jsJokes = [
    {
        id: 1,
        title: "🎶For the first JavaScriptmas this joke was told to me!🎶",
        setup: "What's a ghoasts favorite data type?",
        punchline: "A BOOlean.",
    },
    {
        id: 2,
        title: "🎶You're a mean one, JavaScript🎶",
        setup: "What tool do you use to switch versions of node?",
        punchline: "nvm, I figured it out.",
    },
    {
        id: 3,
        title: "🎶All I want for JavaScriptmas is Vue🎶",
        setup: "How do you comfort a JavaScript bug?",
        punchline: "You console it.",
    },
    {
        id: 4,
        title: "🎶Last JavaScriptmas, I gave you my code🎶",
        setup: "Two JavaScript variables are in a bar. I'm sorry I cannot be with you, your so not my Type, one says.",
        punchline: "The other Recasts and they lived happily ever after.",
    },
    {
        id: 5,
        title: "🎶Let us code! Let us code! Let us code!🎶",
        setup: "Why did the React class component feel relieved?",
        punchline: "Because it was now off the hook.",
    },
    {
        id: 6,
        title: "🎶It's the most JavaScript time of the year🎶",
        setup: "Don't trust JavaScript programmers.",
        punchline: "All they do is promises but they never callback.",
    },
    {
        id: 7,
        title: "🎶Rockin' around the JavaScriptmas code🎶",
        setup: "Why did the CoffeeScript developer keep getting lost?",
        punchline: "Because he couldn't find his source without a map.",
    },
    {
        id: 8,
        title: "🎶JavaScript JavaScript JavaScript rocks!🎶",
        setup: "Why did the hungry dev multiply a sitring by an integer?",
        punchline: "He wanted some NaN bread.",
    },
    {
        id: 9,
        title: "🎶I wanna wish you a merry JavaScriptmas🎶",
        setup: "What does a JavaScript developer have in his tea?",
        punchline: "Syntactic sugar",
    },
    {
        id: 10,
        title: "🎶It's beginning to look a lot like JavaScriptmas🎶",
        setup: "Why are JavaScript developers hated?",
        punchline: "They overreact.",
    },
    {
        id: 11,
        title: "🎶Rudolph the red code reindeer🎶",
        setup: "Why did the functional component feel lost?",
        punchline: "Because it didn't know what state it was in!",
    },
    {
        id: 12,
        title: "🎶He's makin' an array, he's checkin' it twice!🎶",
        setup: "Why did the React Higher Order Component give up?",
        punchline: "Because it sur-rendered to the prop-aganda!",
    },
    {
        id: 13,
        title: "🎶Here comes JavaScript, here comes JavaScript right down JavaScript lane!🎶",
        setup: "Why did the react class component feel relieved?",
        punchline: "Because it was now off the hook.",
    },
    {
        id: 14,
        title: "🎶Grandma got hacked by a reindeer!🎶",
        setup: "Why couldn’t the React component understand the joke?",
        punchline: "Because it didn’t get the context.",
    },
    {
        id: 15,
        title: "🎶O come, all ye coders🎶",
        setup: "Why did the jQuery developer never have financial problems?",
        punchline: "Because he was in $.noConflict() mode",
    },
    {
        id: 16,
        title: "🎶We wish you a merry JavaScriptmas!🎶",
        setup: "What did Java say to his son?",
        punchline: "You're a script, kiddie",
    },
    {
        id: 17,
        title: "🎶Kissin' in the code🎶",
        setup: "JavaScript is a lot like English;",
        punchline: "No one knows how to use semicolons properly.",
    },
    {
        id: 18,
        title: "🎶12 Days of JavaScriptmas🎶",
        setup: "",
        punchline: "",
    },
    {
        id: 19,
        title: "🎶Silent night, coding night🎶",
        setup: "Why do JavaScripters wear glasses?",
        punchline: "Because they don't C#",
    },
    {
        id: 20,
        title: "🎶Baby it's code outside🎶",
        setup: "You want to hear a javascript joke?",
        punchline: "I'll callback later.",
    },
    {
        id: 21,
        title: "🎶Do you want to build some code, man?🎶",
        setup: "",
        punchline: "",
    },
    {
        id: 22,
        title: "🎶Have yourself a merry little JavaScriptmas🎶",
        setup: "How did the programmer die in the shower?",
        punchline: "He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
    },
    {
        id: 23,
        title: "🎶I saw mommy coding with Santa Claus🎶",
        setup: "Why do Javascript developers prefer dark mode?",
        punchline: "Because light attracts bugs!",
    },
    {
        id: 24,
        title: "🎶Code of the bells🎶",
        setup: "What is the object-oriented way to become wealthy?",
        punchline: "Inheritance",
    },
    {
        id: 25,
        title: "🎶JavaScript coded by an open fire🎶",
        setup: "Enough jokes.",
        punchline: "Spend time with your loved ones.",
    },
]
